- id: '1710788675192'
  alias: Power - Reset grid price variables at new month
  description: Resets all the variables associated with keeping track of grid company
    bill, such as max-hours, max-hours dates, variable cost sum
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.tibber_energy_consumption_this_month
    below: 0.1
  condition: []
  action:
  - service: input_number.set_value
    metadata: {}
    data:
      value: 0
    target:
      entity_id:
      - input_number.power_monthly_highest_max_hour_1
      - input_number.power_monthly_highest_max_hour_2
      - input_number.power_monthly_highest_max_hour_3
      - input_number.power_grid_monthly_variable_price
  - service: input_datetime.set_datetime
    target:
      entity_id:
      - input_datetime.power_monthly_highest_max_hour_1
      - input_datetime.power_monthly_highest_max_hour_2
      - input_datetime.power_monthly_highest_max_hour_3
    data:
      timestamp: '{{ now().replace(hour=0, minute=0, second=0, microsecond=0).timestamp()
        }}'
  mode: single

