- id: '1710788675192'
  alias: Power - Reset grid price variables at new month
  description: Resets all the variables associated with keeping track of grid company
    bill, such as max-hours, max-hours dates, variable cost sum
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.tibber_monthly_cost
    below: 0.1
  condition: []
  action:
  - service: input_number.set_value
    data:
      value: 0
    target:
      entity_id:
      - input_number.power_monthly_highest_max_hour_1
      - input_number.power_monthly_highest_max_hour_2
      - input_number.power_monthly_highest_max_hour_3
      - input_number.power_grid_monthly_variable_price
  - service: input_datetime.set_datetime
    target:
      entity_id:
      - input_datetime.power_monthly_highest_max_hour_1
      - input_datetime.power_monthly_highest_max_hour_2
      - input_datetime.power_monthly_highest_max_hour_3
    data:
      timestamp: '{{ now().replace(hour=0, minute=0, second=0, microsecond=0).timestamp()
        }}'
  mode: single
- id: '1711099990422'
  alias: Bedroom - Handle heated Sheet remote control on/off/up/down
  description: Controls the behavior of the heated sheet on/off/longer/shorter.
  trigger:
  - device_id: 6d307d44235cf1a24620d50d7aead120
    domain: hue
    platform: device
    type: short_release
    subtype: 1
    unique_id: fbb8e052-aef2-4e2d-9f7e-5b64ff5b87dd
    id: 'on'
  - device_id: 6d307d44235cf1a24620d50d7aead120
    domain: hue
    platform: device
    type: short_release
    subtype: 4
    unique_id: 3ae253c0-9a8d-42c8-a97d-1c0c8f34d3ba
    id: 'off'
  - device_id: 6d307d44235cf1a24620d50d7aead120
    domain: hue
    platform: device
    type: short_release
    subtype: 2
    unique_id: f2c150a3-71ea-4394-a111-84dcda198d42
    id: up
  - device_id: 6d307d44235cf1a24620d50d7aead120
    domain: hue
    platform: device
    type: short_release
    subtype: 3
    unique_id: 36db30f0-b90d-4ec4-907b-983978a747af
    id: down
  condition: []
  action:
  - if:
    - condition: trigger
      id:
      - 'on'
    then:
    - service: script.bedroom_heated_sheet_control
      data:
        command: 'on'
        increase: 00:30:00
  - if:
    - condition: trigger
      id:
      - 'off'
    then:
    - service: script.bedroom_heated_sheet_control
      data:
        command: 'off'
  - if:
    - condition: trigger
      id:
      - up
    then:
    - service: script.bedroom_heated_sheet_control
      data:
        command: up
        increase: 00:30:00
  - if:
    - condition: trigger
      id:
      - down
    then:
    - service: script.bedroom_heated_sheet_control
      data:
        command: down
        decrease: 00:10:00
  mode: queued
- id: '1711100194488'
  alias: Bedroom - Handle heated sheet timer start/finish
  description: ''
  trigger:
  - platform: state
    entity_id:
    - timer.heated_sheet_timer
    from: idle
    to: active
    id: starts
  - platform: state
    entity_id:
    - timer.heated_sheet_timer
    to: idle
    from: active
    id: finishes
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - starts
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.heated_sheet_switch
      alias: STARTS
    - conditions:
      - condition: trigger
        id:
        - finishes
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.heated_sheet_switch
      alias: FINISHES
  mode: single
- id: '1712088086740'
  alias: System - Daily reset & maintenance tasks
  description: Performs resets, upgrades and maintenance at a daily time set by the
    provided time-helper.
  trigger:
  - platform: time
    at: input_datetime.system_daily_reset_time
  condition: []
  action:
  - service: script.lights_reset_overrides
    data: {}
  - service: input_boolean.turn_off
    target:
      entity_id:
      - input_boolean.party_mode_enable
      - input_boolean.lights_movie_mode
      - input_boolean.lights_dining_mode
      - input_boolean.lights_cooking_mode
    data: {}
  - service: script.deselect_floorplan_room
    data: {}
  - service: input_select.select_option
    data:
      option: 'off'
    target:
      entity_id: input_select.office_mode_select
  - service: input_select.select_option
    target:
      entity_id: input_select.bathroom_mode_select
    data:
      option: 'off'
  - service: script.speakers_unjoin_all
    metadata: {}
    data: {}
  - service: input_select.select_option
    metadata: {}
    data:
      option: Living room
    target:
      entity_id: input_select.audio_speaker_select
  mode: single
- id: '1712148158938'
  alias: Office - Handle Light mode change
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.office_mode_select
  condition: []
  action:
  - service: script.office_control_homey_ledring
    data:
      setting: '{{ states(''input_select.office_mode_select'') }}'
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ is_state(''input_select.office_mode_select'', ''off'')
          }}'
      sequence:
      - service: light.turn_off
        target:
          entity_id:
          - light.pendants_office
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.lights_override_office
      alias: 'off'
    - conditions:
      - condition: template
        value_template: '{{ is_state(''input_select.office_mode_select'', ''focus'')
          }}'
      sequence:
      - service: light.turn_on
        data:
          brightness_pct: 50
        target:
          entity_id: light.pendants_office
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.lights_override_office
      alias: focus
    - conditions:
      - condition: template
        value_template: '{{ is_state(''input_select.office_mode_select'', ''gaming'')
          }}'
      sequence:
      - service: light.turn_on
        data:
          brightness_pct: 10
        target:
          entity_id: light.pendants_office
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.lights_override_office
      alias: gaming
  mode: single
- id: '1712303592468'
  alias: Bathroom - Handle light mode change
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.bathroom_mode_select
  condition: []
  action:
  - service: script.bathroom_control_light_mode
    data:
      setting: '{{ states(''input_select.bathroom_mode_select'') }}'
  mode: single
- id: '1713336556278'
  alias: Tablet charge-switch ON/OFF
  description: Turns the tablet charge-switch ON if it is below 20%, and OFF if it
    is above 80%.
  trigger:
  - alias: Below 20 pcnt
    platform: numeric_state
    entity_id:
    - sensor.lenovo_tab_m10_battery
    below: 20
    id: below-20-pcnt
  - alias: Above 80 pcnt
    platform: numeric_state
    entity_id:
    - sensor.lenovo_tab_m10_battery
    above: 80
    id: above-80-pcnt
  condition: []
  action:
  - alias: Choose switch ON or OFF
    choose:
    - conditions:
      - condition: trigger
        id:
        - below-20-pcnt
      sequence:
      - alias: Turn Tablet charge-switch ON
        type: turn_on
        device_id: e7edcdcfed58b7cedd57142e4434bc5d
        entity_id: 82cd7e59d5a8397fb6ee740fcd273acf
        domain: switch
    - conditions:
      - condition: trigger
        id:
        - above-80-pcnt
      sequence:
      - alias: Turn charge-switch OFF
        type: turn_off
        device_id: e7edcdcfed58b7cedd57142e4434bc5d
        entity_id: 82cd7e59d5a8397fb6ee740fcd273acf
        domain: switch
  mode: single
- id: '1713360573726'
  alias: Wake-up alarm - Time triggered actions
  description: Handles all time-triggered actions associated with the wake-up alarm,
    such as turning on the lights and audio media.
  trigger:
  - platform: time
    at: input_datetime.wakeup_alarm_weekdays
    id: alarm
  - platform: time
    at: sensor.wakeup_light_start_time
    id: 10min-before
  - platform: time
    at: sensor.wakeup_last_call_time
    id: 30min-after
  condition:
  - condition: state
    entity_id: input_boolean.wakeup_alarm_active
    state: 'on'
  action:
  - if:
    - condition: trigger
      id:
      - 10min-before
    then:
    - service: light.turn_on
      data:
        brightness_pct: 3
      target:
        entity_id: light.pendant_bedroom
    - service: light.turn_on
      data:
        brightness_pct: 25
        transition: 300
      target:
        entity_id: light.pendant_bedroom
  - if:
    - condition: trigger
      id:
      - 30min-after
    then:
    - service: script.masterdim_script
      data:
        manual_override: '{{ is_state(''input_boolean.wakeup_alarm_active'', ''on'')
          }}'
        light_entity: light.pendant_bedroom
        brightness: 100
  mode: single
