# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

# Load frontend themes from the themes folder
frontend:
  # Default template themes, commented out
  # themes: !include_dir_merge_named themes
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
    - /local/community/lovelace-card-mod/card-mod.js

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

# Enabling Python-scripts with an Integration is obsolete.
# Add scripts to <config>/python_scripts
# The following line enables Python-scripts.
python_script:

# Enables logging from Python-scripts.
logger:
  default: info

lovelace:
  mode: storage
  dashboards:
    dashboard-tablet:
      mode: yaml
      filename: dashboard-tablet.yaml
      title: Tablet Dashboard
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
    tablet-test:
      mode: yaml
      filename: tablet-test.yaml
      title: Tablet Test
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
      