# Loads default set of integrations. Do not remove.
default_config:

# HOME ASSISTANT SYSTEM
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
template: !include templates.yaml

# TEXT TO SPEECH
tts:
  - platform: google_translate

# FRONTEND
# Load frontend themes from the themes folder
frontend:
  # Default template themes, commented out
  # themes: !include_dir_merge_named themes
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
    - /local/community/lovelace-card-mod/card-mod.js

# USER INTERFACES
lovelace:
  mode: storage
  dashboards:
    dashboard-tablet:
      mode: yaml
      filename: dashboard-tablet.yaml
      title: Tablet Dashboard
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
    tablet-test:
      mode: yaml
      filename: tablet-test.yaml
      title: Tablet Test
      icon: mdi:tablet-dashboard
      show_in_sidebar: true

# PYTHON SCRIPTS
# Add scripts to <config>/python_scripts. Also add its entry to services.yaml in same folder.
# Enabling Python-scripts with an Integration is obsolete. This enables Python-scripts:
python_script:
# Enables logging from Python-scripts.
logger:
  default: info

# ROBOT VACUUM CAMERA
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ['all']
    attributes:
      - calibration_points

