# Loads default set of integrations. Do not remove.
default_config:

# HOME ASSISTANT SYSTEM
automation: !include automations.yaml
automation modules: !include_dir_merge_list automation_modules/
scene: !include scenes.yaml
sensor: !include sensors.yaml
script: !include scripts.yaml
template: !include templates.yaml
input_boolean: !include input_boolean.yaml

# TEXT TO SPEECH
tts:
  - platform: google_translate

# FRONTEND
frontend:
  # Load frontend themes from the themes folder
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js

# USER INTERFACES
lovelace:
  mode: storage
  dashboards:
    dashboard-tablet:
      mode: yaml
      filename: dashboard-tablet.yaml
      title: Tablet
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
    dashboard-mobile:
      mode: yaml
      filename: dashboard-mobile.yaml
      title: Mobile
      icon: mdi:cellphone
      show_in_sidebar: true

# PYTHON SCRIPTS
# Add scripts to <config>/python_scripts. Also add its entry to services.yaml in same folder.
# Enabling Python-scripts with an Integration is obsolete. This enables Python-scripts:
python_script:
# Enables logging from Python-scripts.
logger:
  default: info

#spotcast:
#  sp_dc: !secret spotify_sp_dc
#  sp_key: !secret spotify_sp_key
#  country: 'NO'

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 20
    icon: mdi:home

rest_command:
  ledring_off:
    url: !secret homey_ledring_off
    method: POST
  ledring_focus:
    url: !secret homey_ledring_focus
    method: POST
  ledring_gaming:
    url: !secret homey_ledring_gaming
    method: POST
  ledring_attention:
    url: !secret homey_ledring_attention
    method: POST
  ledring_state:
    url: !secret homey_ledring_state
    method: GET

# --- 
# ROBOROCK ROOM MAPPING FROM miiocli
# Roborock = Xiaomi . miiocli is a Xiaomi tool.
# If room mappings change, search around how to do it again.
# Custom integration such as 'xiaomi_cloud_map_extractor' has been removed
# ROOMS:
# Entry: 16, '107001052585' 
# Kitchen: 17, '107001052584'
# Living room: 18, '107001074474'
# Guest room: 19, '107001074480' 
# Bedroom: 20, '107001052586'
# Office: 21, '107001074479'
# ---
## Fan options - Xiaomi
# Silent, Standard, Medium, Turbo
## Fan options - Roborock equivalent
# Quiet, Balanced, Turbo, Max
## Statuses
# "Returning home", "Segment cleaning"
# ---
