# Entur / Ruter holdeplass sanntidsdata om avganger
- platform: entur_public_transport
  name: Ruter
  expand_platforms: true
  show_on_map: true
  number_of_departures: 4
  stop_ids:
    - "NSR:StopPlace:58185" # Sandaker senter
    - "NSR:StopPlace:58256" # Torshov
    - "NSR:StopPlace:6404" # Haarklous plass
    #- "NSR:StopPlace:58195" # Storo

# Tibber future prices - Electricity provider
- platform: rest
  name: Tibber Prices
  resource: https://api.tibber.com/v1-beta/gql
  method: POST
  payload: '{ "query": "{ viewer { homes { currentSubscription { status priceInfo { current { total } today { total } tomorrow { total } } } } } }" }'
  json_attributes_path: "$.data.viewer.homes[0].currentSubscription.priceInfo"
  json_attributes:
    - today
    - tomorrow
  value_template: "{{ value_json.data.viewer.homes[0].currentSubscription.priceInfo.current.total | float }}"
  scan_interval: 30
  headers:
    Authorization: !secret tibber_token
    Content-Type: application/json
    User-Agent: REST
  unit_of_measurement: NOK/kWh

# Elvia grid company - "Fastledd" ("fixedPrice") limits and prices
# Requests should not exceed 200/hour
# - 2024-03-11T15:00:00 - 2024-03-11T16:00:00 fungerer som StartTime - EndTime, men da får jeg tilbake 16-17
# - 2024-03-11T15:00:00+01:00 - 2024-03-11T16:00:00+01:00 derimot gir errors. "is not valid for EndTime."
- platform: rest
  name: Elvia fixed prices raw
  unique_id: elvia_fixed_prices_raw
  icon: mdi:transmission-tower
  scan_interval: 60
  # Request
  resource: https://elvia.azure-api.net/grid-tariff/digin/api/1.0/tariffquery
  method: GET
  headers:
    X-API-Key: !secret elvia_api_key
  params:
    TariffKey: standard
    Range: today
  # Response
  value_template: >
    {{ value_json.gridTariff.tariffPrice.priceInfo.fixedPrices[0].startDate }}
  json_attributes_path: "$.gridTariff.tariffPrice.priceInfo.fixedPrices[0]"
  json_attributes:
    - priceLevels

# Elvia hourly, flat variable pricing (energiledd) - NOK/kWh
# As of initial configuration (11.03.2024), valid for Jan.-March 2024 there are two pricings:
# - 0.3959 NOK/kWh 0600-2200 on weekdays
# - 0.3209 NOK/kWh 2200-0600 on weekdays. Also for entire weekends and public holidays.
# The price is including tax and fees.
# This API request fetches the price dynamically for the current hour
# It will automatically get new prices when the original model is outdated.
- platform: rest
  name: Elvia variable pricing, this hour
  unique_id: elvia_variable_pricing_this_hour
  icon: mdi:transmission-tower
  scan_interval: 60
  # Request
  resource: https://elvia.azure-api.net/grid-tariff/digin/api/1.0/tariffquery
  method: GET
  headers:
    X-API-Key: !secret elvia_api_key
  params:
    TariffKey: standard
    # This calculation handles subtracting TZ-info from the target datetimes
    # Accepted format: yyyy-mm-ddTHH:MM:SS. Adding TZ-info is not supported (+HH:MM)
    # However, the returned time is adjusted for timezone.
    StartTime: >
      {% set tz_hours = now().isoformat().split('+')[1].split(':')[0] | int %}
      {{ ( now() + timedelta(hours=(0-tz_hours)) ).strftime('%Y-%m-%dT%H:00:00') }}
    EndTime: >
      {% set tz_hours = now().isoformat().split('+')[1].split(':')[0] | int %}
      {{ ( now() + timedelta(hours=(1-tz_hours )) ).strftime('%Y-%m-%dT%H:00:00') }}
  # Response
  value_template: >
    {{ value_json.gridTariff.tariffPrice.hours[0].energyPrice.total }}
  json_attributes_path: "$.gridTariff.tariffPrice.hours[0]"
  json_attributes:
  - shortName
  - startTime
  - expiredAt
  - isPublicHoliday

# Elvia variable prices full list, every hour forecast: Today & tomorrow
- platform: rest
  name: Elvia variable pricing, full list
  unique_id: elvia_variable_pricing_full_list
  icon: mdi:transmission-tower
  scan_interval: 60
  # Request
  resource: https://elvia.azure-api.net/grid-tariff/digin/api/1.0/tariffquery
  method: GET
  headers:
    X-API-Key: !secret elvia_api_key
  params:
    TariffKey: standard
    StartTime: >
      {% set tz_hours = now().isoformat().split('+')[1].split(':')[0] | int %}
      {% set today_start = now().replace(hour=0, minute=0, second=0, microsecond=0) %}
      {{ ( today_start + timedelta(hours=(0-tz_hours)) ).strftime('%Y-%m-%dT%H:00:00') }}
    EndTime: >
      {% set tz_hours = now().isoformat().split('+')[1].split(':')[0] | int %}
      {% set tomorrow_end = (now() + timedelta(days=2)).replace(hour=0, minute=0, second=0, microsecond=0) %}
      {{ ( tomorrow_end + timedelta(hours=(0-tz_hours)) ).strftime('%Y-%m-%dT%H:00:00') }}
  # Response
  value_template: >
    {% set hour = now().hour %}
    {{ value_json.gridTariff.tariffPrice.hours[hour].energyPrice.total }}
  json_attributes_path: "$.gridTariff.tariffPrice"
  json_attributes:
  - hours
  
# Time and date as sensors
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"

# TEMPLATE SENSORS ARE DEPRECATED!
# - platform: template
#   sensors: []
# Instead: Make sensor templates in templates.yaml
# NOTE: "Temperature apartment avg" moved to templates.yaml to allow rounding to 1 decimal