# Entur / Ruter holdeplass sanntidsdata om avganger
- platform: entur_public_transport
  name: Ruter
  expand_platforms: true
  show_on_map: true
  number_of_departures: 4
  stop_ids:
    - "NSR:StopPlace:58185" # Sandaker senter
    - "NSR:StopPlace:58256" # Torshov
    - "NSR:StopPlace:6404" # Haarklous plass
    - "NSR:StopPlace:58195" # Storo

# Tibber future prices
- platform: rest
  name: Tibber Prices
  resource: https://api.tibber.com/v1-beta/gql
  method: POST
  payload: '{ "query": "{ viewer { homes { currentSubscription { status priceInfo { current { total } today { total } tomorrow { total } } } } } }" }'
  json_attributes_path: "$.data.viewer.homes[0].currentSubscription.priceInfo"
  json_attributes:
    - today
    - tomorrow
  value_template: "{{ value_json.data.viewer.homes[0].currentSubscription.priceInfo.current.total | float }}"
  scan_interval: 30
  headers:
    Authorization: !secret tibber_token
    Content-Type: application/json
    User-Agent: REST
  unit_of_measurement: NOK/kWh

# Time and date as sensors
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
    - "beat"

# All template sensors
- platform: template
  sensors:
    # Readable string for week-day, as sensor
    day:
      value_template: >
        {% set days = ["Mandag", "Tirsdag", "Onsdag", "Torsdag", "Fredag", "Lørdag", "Søndag"] %}
        {{ days[now().weekday()] }}
    
    # Readable string for month, as sensor
    month:
      value_template: >
        {% set months = ["januar", "februar", "mars", "april", "mai", "juni", "juli", "august", "september", "oktober", "november", "desember"] %}
        {{ months[now().month-1] }}
    
    # Formats the week-day and date into a humanly readable sentence for UI, as sensor
    date_string:
      friendly_name: "Full Date"
      value_template: "{{ states('sensor.day') }}, {{ now().day }}.  {{ states('sensor.month') }} {{ now().year }}"
    
    # Temperature sensor for Kitchen Heater
    kitchen_temperature:
      friendly_name: "Kitchen Heater measured temperature"
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('climate.kitchen_heater', 'current_temperature') }}"
      device_class: temperature

    # Temperature sensor for current outdoor weather from weather integration
    outdoor_temperature:
      friendly_name: "Outdoor current temperature"
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('weather.yr_weather_home', 'temperature') }}"
      device_class: temperature

    # Finds the current setting of the physical remote for the heated sheet
    heated_sheet_setting:
      friendly_name: "Heated Sheet - Control setting"
      value_template: >-
        {% if states('sensor.heated_sheet_switch_switch_0_power')|float >= 0 and states('sensor.heated_sheet_switch_switch_0_power')|float < 1 %}
          Off
        {% elif states('sensor.heated_sheet_switch_switch_0_power')|float >= 15 and states('sensor.heated_sheet_switch_switch_0_power')|float <= 20 %}
          #1
        {% elif states('sensor.heated_sheet_switch_switch_0_power')|float >= 28 and states('sensor.heated_sheet_switch_switch_0_power')|float <= 40 %}
          Feet
        {% elif states('sensor.heated_sheet_switch_switch_0_power')|float >= 50 and states('sensor.heated_sheet_switch_switch_0_power')|float <= 80 %}
          #2
        {% else %}
          On
        {% endif %}
    
    # FLOORPLAN LIGHT BRIGHTNESS INTERVAL-LEVEL SENSORS
    # Defined here. Automatically updated by automations.
    dim_pendant_bedroom:
      friendly_name: "Bedroom pendant brightness level"
      value_template: "{{ states('sensor.dim_pendant_bedroom') }}"
      unit_of_measurement: '%'
    
    dim_pendants_office:
      friendly_name: "Office pendants brightness level"
      value_template: "{{ states('sensor.dim_pendants_office') }}"
      unit_of_measurement: '%'
    
    dim_pendant_guest:
      friendly_name: "Guest pendant brightness level"
      value_template: "{{ states('sensor.dim_pendant_guest') }}"
      unit_of_measurement: '%'
    
    dim_downlight_toilet:
      friendly_name: " brightness level"
      value_template: "{{ states('sensor.dim_downlight_toilet') }}"
      unit_of_measurement: '%'

    dim_downlights_bath:
      friendly_name: "Guest pendant brightness level"
      value_template: "{{ states('sensor.dim_downlights_bath') }}"
      unit_of_measurement: '%'

    dim_lightstrip_bath:
      friendly_name: "Guest pendant brightness level"
      value_template: "{{ states('sensor.dim_lightstrip_bath') }}"
      unit_of_measurement: '%'

    dim_downlights_entry:
      friendly_name: "Entry downlights brightness level"
      value_template: "{{ states('sensor.dim_downlights_entry') }}"
      unit_of_measurement: '%'
    
    dim_spottrack_living:
      friendly_name: "Living room spot-track brightness level"
      value_template: "{{ states('sensor.dim_spottrack4_living') }}"
      unit_of_measurement: '%'
    
    dim_downlights_living:
      friendly_name: "Living room downlights brightness level"
      value_template: "{{ states('sensor.dim_downlights_living') }}"
      unit_of_measurement: '%'
    
    dim_pendants_dining:
      friendly_name: "Dining pendants brightness level"
      value_template: "{{ states('sensor.dim_pendants_dining') }}"
      unit_of_measurement: '%'

    dim_pendants_kitchen:
      friendly_name: "Dining pendants brightness level"
      value_template: "{{ states('sensor.dim_pendants_kitchen') }}"
      unit_of_measurement: '%'
    
    dim_spottrack_kitchen:
      friendly_name: "Dining pendants brightness level"
      value_template: "{{ states('sensor.dim_spottrack_kitchen') }}"
      unit_of_measurement: '%'

    dim_lightstrip_kitchen:
      friendly_name: "Dining pendants brightness level"
      value_template: "{{ states('sensor.dim_lightstrip_kitchen') }}"
      unit_of_measurement: '%'
    
