blueprint:
  name: Masterdim Light Brigthness
  description: Adjusts the brightness of a light entity if it's turned on.
  domain: automation
  input:
    light_entity:
      name: Light Entity
      description: The light entity to adjust.
      selector:
        entity:
          filter:
            domain: light
    brightness_value:
      name: Brightness Value
      description: The brightness value to set.
      default: 50
      selector:
        number:
          min: 1
          max: 100
          step: 1

trigger:
  platform: state
  entity_id: !input light_entity
  from: "on"
  to: "on"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data:
              brightness_pct: !input brightness_value
