# This whole blueprint is not working, and is work in progress
blueprint:
  name: Masterdim script
  description: >-
    A script that takes brightness and a light-entity as input, checks if that light is on.
    If it is, then the light is dimmed to the input brightness.
  domain: script
  #source_url: https://github.com/home-assistant/core/blob/master/homeassistant/components/script/blueprints/confirmable_notification.yaml
  author: iZwag
  input:
    light_entity:
      name: Target light entity
      description: The light-entity that will be checked and controlled.
      selector:
        entity:
          filter:
            - domain: light
    brightness:
      name: Brightness (percent)
      description: An integer percent-value that the target light will be set to if it is on.
      selector:
        number:
          min: 1
          max: 100

sequence:
- choose:
    - conditions:
        - condition: state
          entity_id: !input light_entity
          state: "on"
      sequence:
        - service: light.turn_on
          data:
            "entity_id": !input 'light_entity'
            "brightness_pct": !input 'brightness'

mode: single
icon: mdi:brightness-auto