# Fixed
- id: "1702582088817"
  alias: Spot-track6 to Lightstrip shelf ON/OFF/DIM
  description:
    Handles the mirroring of turning ON/OFF and dimming the brightness
    of the shelf lightning when the Spot-track is interacted with.
  trigger:
    - platform: device
      type: turned_off
      device_id: 3b314b934fee629a9f95316c027e2ad0
      entity_id: 6a483694307cabbe1f0abc602ed6b17f
      domain: light
      id: turned-off
    - platform: state
      entity_id:
        - light.spottrack6_kitchen
      attribute: brightness
      id: turned-on-dimmed
  condition: []
  action:
    - choose:
        - conditions:
            - condition: trigger
              id:
                - turned-off
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.lightstrip_kitchen
              data: {}
        - conditions:
            - condition: trigger
              id:
                - turned-on-dimmed
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.lightstrip_kitchen
              data:
                brightness: "{{ trigger.to_state.attributes.brightness }}"
  mode: single
# Fixed
- id: "1702586142625"
  alias: Tablet charge-switch ON/OFF
  description:
    Turns the tablet charge-switch ON if it is below 15%, and OFF if it
    is above 85%.
  trigger:
    - alias: Below 15 pcnt
      platform: numeric_state
      entity_id:
        - sensor.lenovo_wall_tablet_battery_level
      below: 15
      id: below-15-pcnt
    - alias: Above 85 pcnt
      platform: numeric_state
      entity_id:
        - sensor.lenovo_wall_tablet_battery_level
      above: 85
      id: above-85-pcnt
  condition: []
  action:
    - alias: Choose switch ON or OFF
      choose:
        - conditions:
            - condition: trigger
              id:
                - below-15-pcnt
          sequence:
            - alias: Turn Tablet charge-switch ON
              type: turn_on
              device_id: e7edcdcfed58b7cedd57142e4434bc5d
              entity_id: 82cd7e59d5a8397fb6ee740fcd273acf
              domain: switch
        - conditions:
            - condition: trigger
              id:
                - above-85-pcnt
          sequence:
            - alias: Turn charge-switch OFF
              type: turn_off
              device_id: e7edcdcfed58b7cedd57142e4434bc5d
              entity_id: 82cd7e59d5a8397fb6ee740fcd273acf
              domain: switch
  mode: single
# TODO
- id: "1689104769483"
  alias: Tablet motion turns screen ON/OFF
  description: ""
  trigger:
    - platform: state
      entity_id:
        - switch.lenovo_tab_m10_fhd_plus_motion_detection
      to: "on"
      id: tablet-motion-on
      alias: Tablet motion ON
    - platform: state
      entity_id:
        - switch.lenovo_tab_m10_fhd_plus_motion_detection
      to: "off"
      alias: Tablet motion OFF
      id: tablet-motion-off
  condition: []
  action:
    - choose:
        - conditions:
            - condition: trigger
              id:
                - tablet-motion-on
          sequence:
            - service: switch.turn_on
              data: {}
              target:
                entity_id: switch.lenovo_tab_m10_fhd_plus_screen
              alias: Turn Tablet screen ON
        - conditions:
            - condition: trigger
              id:
                - tablet-motion-off
          sequence:
            - service: switch.turn_off
              data: {}
              target:
                entity_id: switch.lenovo_tab_m10_fhd_plus_screen
              alias: Turn tablet screen OFF
  mode: single
# Fixed
- id: "1702588010634"
  alias: Veranda dusk-ON/dawn-OFF
  description: ""
  trigger:
    - platform: time
      at: sensor.sun_next_setting
      id: sun-down
    - platform: time
      at: sensor.sun_next_dawn
      id: sun-dawn
  condition: []
  action:
    - choose:
        - conditions:
            - condition: trigger
              id:
                - sun-down
          sequence:
            - type: turn_on
              device_id: e115fa7aa6cbeb1d373b0ab0d7c808d0
              entity_id: f7e543af2bb56185534ecba1eb4a0c2d
              domain: switch
        - conditions:
            - condition: trigger
              id:
                - sun-dawn
          sequence:
            - type: turn_off
              device_id: e115fa7aa6cbeb1d373b0ab0d7c808d0
              entity_id: f7e543af2bb56185534ecba1eb4a0c2d
              domain: switch
  mode: single
